# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
### eos_pacman Module
#
# This module creates the mirrorlists and initializes the pacman keyring
#

---

# When true, each line of output from the script will be displayed in calamares
#
userOutput: true
